services:
  - type: web
    name: pepe-scraper-app
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_SECRET
        generateValue: true
      - key: ADMIN_KEY
        sync: false
      - key: PYTHON_BIN
        value: python
