name: Run Blinkit Scraper

on:
  schedule:
    - cron: "0 * * * *"  # every hour at minute 0 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install

      # 3a. Install system dependencies needed for Chromium
      - name: Install system packages for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libatk1.0-0 libcups2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 \
            libpangocairo-1.0-0 libpango-1.0-0 libgtk-3-0 libasound2t64 fonts-liberation fonts-dejavu \
            wget curl unzip

      - name: Run Blinkit scraper
        run: python blinkit_scraper.py

      - name: Commit and push updated CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blinkit_data.csv
          git diff-index --quiet HEAD || git commit -m "Auto-update Blinkit CSV"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Amal-GBL/PricePulse.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
