name: Run Scrapers

on:
  schedule:
    - cron: "0 * * * *"   # every hour at minute 0 UTC
  workflow_dispatch:

jobs:
  scrape-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run all scrapers
      - name: Run scrapers
        run: python run_all_scrapers.py

      # 5️⃣ Configure git to push
      - name: Configure Git for Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      # 6️⃣ Commit and push CSVs
      - name: Commit and push CSVs
        run: |
          git add *.csv
          git commit -m "Auto-update scraped CSVs" || echo "No changes to commit"
          git push origin main
