name: Run scrapers

on:
  schedule:
    - cron: "0 * * * *"   # every hour (UTC)
  workflow_dispatch:      # allow manual trigger from GitHub UI

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scrapers
        run: python run_all_scrapers.py

      - name: Commit updated CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git commit -m "Auto-update scraped CSVs" || echo "No changes to commit"
          git push
