name: Run Scrapers

on:
  schedule:
    - cron: "0 * * * *"   # every hour at minute 0 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install

      # 3a. Install system dependencies needed for Playwright/Chromium
      - name: Install system packages for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libatk1.0-0 libcups2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 \
            libpangocairo-1.0-0 libpango-1.0-0 libgtk-3-0 libasound2 fonts-liberation fonts-dejavu \
            wget curl unzip \
            libatk-bridge2.0-0 libgtk-3-bin libxss1 libx11-xcb1 libxcb-dri3-0 libdrm2 libatspi2.0-0 \
            ca-certificates fonts-noto-color-emoji \
            libxi6 libxtst6 libxshmfence1 xvfb

      # 4. Run all scrapers with xvfb (non-headless Chromium support)
      - name: Run all scrapers
        run: xvfb-run -a python run_all_scrapers.py

      # 5. Commit and push updated CSVs
      - name: Commit and push updated CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git diff-index --quiet HEAD || git commit -m "Auto-update scraped CSVs"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Amal-GBL/PricePulse.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
