name: Run Scrapers

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pricepulse-scrapers .

      - name: Run scrapers in container
        run: |
          docker run \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            pricepulse-scrapers

      - name: Commit updated CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git diff-index --quiet HEAD || git commit -m "Auto-update scraped CSVs"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Amal-GBL/PricePulse.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
