name: Run Scrapers

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          # Install Chromium + system deps
          playwright install --with-deps chromium

      - name: Run scrapers
        run: |
          python run_all_scrapers.py

      - name: Commit and push updated CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git diff-index --quiet HEAD || git commit -m "Auto-update scraped CSVs"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Amal-GBL/PricePulse.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
